CREATE TABLE IF NOT EXISTS tf_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS tf_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_user_tenant_username
    UNIQUE (tenant_id, username),

    CONSTRAINT fk_user_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id)
    );

CREATE TABLE IF NOT EXISTS tf_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    ticket_no VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(5000),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    priority VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    created_by BIGINT,
    customer_id BIGINT,
    assignee_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_ticket_tenant_no
    UNIQUE (tenant_id, ticket_no),

    CONSTRAINT fk_ticket_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id),

    CONSTRAINT fk_ticket_assignee
    FOREIGN KEY (assignee_id)
    REFERENCES tf_user(id)
    );

CREATE TABLE IF NOT EXISTS tf_ticket_comment (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                 tenant_id BIGINT NOT NULL,

                                                 ticket_id BIGINT NOT NULL,

                                                 author_id BIGINT NOT NULL,

                                                 content VARCHAR(5000) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_comment_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id),

    CONSTRAINT fk_comment_ticket
    FOREIGN KEY (ticket_id)
    REFERENCES tf_ticket(id),

    CONSTRAINT fk_comment_author
    FOREIGN KEY (author_id)
    REFERENCES tf_user(id)
    );

CREATE TABLE IF NOT EXISTS tf_customer (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           tenant_id BIGINT NOT NULL,
                                           email VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_customer_tenant_email
    UNIQUE (tenant_id, email),

    CONSTRAINT fk_customer_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id)
    );

CREATE TABLE IF NOT EXISTS tf_ticket_operation (
                                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   tenant_id BIGINT NOT NULL,
                                                   ticket_id BIGINT NOT NULL,
                                                   operator_type VARCHAR(16) NOT NULL,
    operator_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    from_value VARCHAR(64),
    to_value VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_operation_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id),

    CONSTRAINT fk_operation_ticket
    FOREIGN KEY (ticket_id)
    REFERENCES tf_ticket(id)
    );

CREATE TABLE IF NOT EXISTS tf_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    permission_group VARCHAR(32) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_permission_code
    UNIQUE (code)
    );

CREATE TABLE IF NOT EXISTS tf_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_role_tenant_code
    UNIQUE (tenant_id, code),

    CONSTRAINT fk_role_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id)
    );

CREATE TABLE IF NOT EXISTS tf_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_role_permission
    UNIQUE (tenant_id, role_id, permission_id),

    CONSTRAINT fk_role_permission_role
    FOREIGN KEY (role_id)
    REFERENCES tf_role(id),

    CONSTRAINT fk_role_permission_permission
    FOREIGN KEY (permission_id)
    REFERENCES tf_permission(id)
    );

CREATE TABLE IF NOT EXISTS tf_member_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_member_role
    UNIQUE (tenant_id, member_id, role_id),

    CONSTRAINT fk_member_role_member
    FOREIGN KEY (member_id)
    REFERENCES tf_user(id),

    CONSTRAINT fk_member_role_role
    FOREIGN KEY (role_id)
    REFERENCES tf_role(id)
    );

CREATE TABLE IF NOT EXISTS tf_sla_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    priority VARCHAR(16) NOT NULL,
    first_response_minutes INT NOT NULL,
    resolution_minutes INT NOT NULL,
    remind_before_minutes INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_sla_tenant_priority
    UNIQUE (tenant_id, priority),

    CONSTRAINT fk_sla_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tf_tenant(id)
    );

-- 权限字典：与 V11 迁移保持一致。
--
-- 这里必须用 MERGE 而不是 INSERT：schema.sql 在每个 Spring 上下文启动时都会重新执行，
-- 而所有测试上下文共用同一个内存库，用 INSERT 会在第二次执行时撞上 uk_permission_code。
MERGE INTO tf_permission (code, name, permission_group, description)
KEY (code)
VALUES
    ('tenant:create',    '创建租户',       '租户', '引导接口，创建新的企业租户'),
    ('user:create',      '创建成员',       '成员', '在租户内创建企业成员账号'),
    ('role:manage',      '管理角色与权限', '权限', '创建角色、调整角色权限、给成员分配角色'),
    ('ticket:read',      '查看工单',       '工单', '查看工单列表、详情与操作记录'),
    ('ticket:create',    '创建工单',       '工单', '创建工单'),
    ('ticket:update',    '编辑工单',       '工单', '修改标题、描述与优先级'),
    ('ticket:assign',    '分配负责人',     '工单', '把工单指派给本租户的其他成员'),
    ('ticket:claim',     '领取工单',       '工单', '把未分配的工单领取给自己'),
    ('ticket:status',    '流转工单状态',   '工单', '推进或回退工单状态'),
    ('ticket:comment',   '发表评论',       '工单', '在工单下发表评论'),
    ('ticket:handle:any','处理任意工单',   '工单', '数据范围：可处理本租户任意工单'),
    ('sla:manage',       '配置 SLA 规则', 'SLA',  '调整本租户各优先级的响应与解决时限');
